export const SHOPPING_CART_INCREASE = 'imprek.SHOPPING_CART_INCREASE';
export const SHOPPING_CART_ADD = 'imprek.SHOPPING_CART_ADD';
export const SHOPPING_CART_DECREASE = 'imprek.SHOPPING_CART_DECREASE';
export const SHOPPING_CART_REMOVE = 'imprek.SHOPPING_CART_REMOVE';
export const SHOPPING_CART_EMPTY = 'imprek.SHOPPING_CART_EMPTY';
