export const SHOPPING_CART_ADD = 'imprek.SHOPPING_CART_ADD';
export const SHOPPING_CART_INCREMENT = 'imprek.SHOPPING_CART_INCREMENT';
export const SHOPPING_CART_DECREMENT = 'imprek.SHOPPING_CART_DECREMENT';
export const SHOPPING_CART_REMOVE = 'imprek.SHOPPING_CART_REMOVE';
