export const GET_PROVINCES = 'imprek.GET_PROVINCES';
export const GET_PROVINCES_MOTO = 'imprek.GET_PROVINCES_MOTO';
export const GET_LOCATIONS_MOTO_SUCCESS = 'imprek.GET_LOCATIONS_MOTO_SUCCESS';
export const GET_LOCATIONS = 'imprek.GET_LOCATIONS';
export const GET_PROVINCES_REQUEST = 'imprek.GET_PROVINCES_REQUEST';
export const GET_LOCATIONS_REQUEST = 'imprek.GET_LOCATIONS_REQUEST';
export const GET_CORREO_BRANCH_OFFICES_REQUEST = 'imprek.GET_CORREO_BRANCH_OFFICES_REQUEST';
export const GET_CORREO_BRANCH_OFFICES_SUCCESS = 'imprek.GET_CORREO_BRANCH_OFFICES_SUCCESS';
