export const MODAL_SCHEDULES_OPEN = 'imprek.MODAL_SCHEDULES_OPEN';
export const MODAL_SCHEDULES_CLOSE = 'imprek.MODAL_SCHEDULES_CLOSE';
export const MODAL_SHIPPINGS_OPEN = 'imprek.MODAL_SHIPPINGS_OPEN';
export const MODAL_SHIPPINGS_CLOSE = 'imprek.MODAL_SHIPPINGS_CLOSE';
export const MODAL_PAYMENT_OPEN = 'imprek.MODAL_PAYMENT_OPEN';
export const MODAL_PAYMENT_CLOSE = 'imprek.MODAL_PAYMENT_CLOSE';
export const MODAL_CLOSE_ALL = 'imprek.MODAL_CLOSE_ALL';
