export const GET_PRODUCT_DETAIL_FAILURE = 'imprek.GET_PRODUCT_DETAIL_FAILURE';
export const GET_PRODUCT_DETAIL_STARTED = 'imprek.GET_PRODUCT_DETAIL_STARTED';
export const GET_PRODUCT_DETAIL_SUCCESS = 'imprek.GET_PRODUCT_DETAIL_SUCCESS';
export const RESET_PRODUCT_DETAIL = 'imprek.RESET_PRODUCT_DETAIL';
