export const GET_PRODUCT_DETAILS_FAILURE = 'imprek.GET_PRODUCT_DETAILS_FAILURE';
export const GET_PRODUCT_DETAILS_STARTED = 'imprek.GET_PRODUCT_DETAILS_STARTED';
export const GET_PRODUCT_DETAILS_SUCCESS = 'imprek.GET_PRODUCT_DETAILS_SUCCESS';
