export const ADD_PURCHASE = 'imprek.ADD_PURCHASE';
export const DELETE_PURCHASE = 'imprek.DELETE_PURCHASE';
export const CREATE_PREFERENCE_REQUEST = 'imprek.CREATE_PREFERENCE_REQUEST';
export const CREATE_PREFERENCE_SUCCESS = 'imprek.CREATE_PREFERENCE_SUCCESS';
export const SET_INPUT_VALUE = 'imprek.SET_INPUT_VALUE';
export const SELECT_PAYMENT = 'imprek.SELECT_PAYMENT';
