export const SAVE_SHIPPING = 'imprek.SAVE_SHIPPING';
export const ADD_PURCHASE = 'imprek.ADD_PURCHASE';
export const CREATE_PREFERENCE_REQUEST = 'imprek.CREATE_PREFERENCE_REQUEST';
export const CREATE_PREFERENCE_SUCCESS = 'imprek.CREATE_PREFERENCE_SUCCESS';
